version: "3"
services:
  db:
    image: postgres:latest
    hostname: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    volumes:
      - postgresVolume:/data/db/postgres

  backend:
    container_name: backend
    build: ./backend-repo/techere
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - db

  # zookeeper:
  #   image: wurstmeister/zookeeper
  #   container_name: zookeeper
  #   ports:
  #     - "2181:2181"

  # kafka:
  #   image: wurstmeister/kafka
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     KAFKA_LISTENERS: PLAINTEXT://:9092
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_CREATE_TOPICS: "topicName:1:1" # 토픽 이름:Partition 개수:Replica 개수
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    depends_on:
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend-repo/build:/usr/share/nginx/html

volumes:
  postgresVolume:
