version: "3"
services:
  backend:
    container_name: backend
    image: TecHERE_Backend/techere
    expose:
      - 8080
    ports:
      - 8080:8080

  nginx:
    container_name: nginx
    image: NGINX
    ports:
      - 80:80
    depends_on:
      - backend
